# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: flutter_app
description: A new Nylo Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  url_launcher: ^6.2.3
  google_fonts: ^6.1.0
  analyzer: ^6.2.0
  intl: ^0.18.1
  nylo_framework: ^5.20.1
  pretty_dio_logger: ^1.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  sidebarx: ^0.16.3
  iconify_flutter: ^0.0.5
  day: ^0.8.0
  animated_bottom_navigation_bar: ^1.3.2
  circular_reveal_animation: ^2.0.1
  auto_size_text: ^3.0.0
  flutter_svg: ^1.1.6
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  #  lints: ^3.0.0
  flutter_test:
    sdk: flutter

# APP ICON - public/assets/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/assets/app_icon/icon.png"
  remove_alpha_ios: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/images/waves/
    - public/assets/images/illustrations/
    - public/assets/app_icon/
    - lang/
    - .env
